[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sold = "0.8.19"
optimizer = true
optimizer_runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
ethereum = "${ETH_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bsctest = "https://data-seed-prebsc-1-s3.bnbchain.org:8545"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
avalanche = "${AVALANCHE_C_CHAIN_RPC_URL}"
base = "${BASE_RPC_URL}"
tron = "${TRON_RPC_URL}"
trontest = "${TRON_TESTNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETH_API_KEY}", chainid = 1 }
bsc = { key = "${BSC_API_KEY}", chainid = 56 }
polygon = { key = "${POLYGON_API_KEY}", chainid = 137 }
arbitrum = { key = "${ARBITRUM_API_KEY}", chainid = 42161 }
optimism = { key = "${OPTIMISM_API_KEY}", chainid = 10 }
base = { key = "${BASE_API_KEY}", chainid = 8453 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = false
