[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.19'
optimizer = true
optimizer_runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
ethereum = "${ETH_RPC_URL}"
bsc = "${BNB_RPC_URL}"
bsctest = "https://data-seed-prebsc-1-s3.bnbchain.org:8545"
polygon = "${POL_RPC_URL}"

[etherscan]
ethereum = { key = "${ETH_API_KEY}", chain = "mainnet" }
bsc = { key = "${BNB_API_KEY}", chain = "bsc" }
bsc-testnet = { key = "${BNB_API_KEY}", chainid = 97 }
polygon = { key = "${POL_API_KEY}", chainid = 137 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = false
